inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'

#Style/Documentationのエラーを解消するため
Style/Documentation:
  Enabled: false
